multitenancy_enabled: false

target: all

server:
  http_listen_address: "0.0.0.0"
  http_listen_port: 4000
  grpc_listen_address: "0.0.0.0"
  grpc_listen_port: 9095

  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
  grpc_server_max_concurrent_streams: 1000

  http_server_read_timeout: "30s"
  http_server_write_timeout: "30s"
  http_server_idle_timeout: "120s"

  log_level: "info"
  log_format: "json"

limits:
  max_query_length: "24h"
  max_query_lookback: "744h"
  max_query_parallelism: 100
  max_flamegraph_nodes_default: 8192
  max_flamegraph_nodes_max: 128000

  ingestion_rate_mb: 1024
  ingestion_burst_size_mb: 2048

  max_label_name_length: 1024
  max_label_value_length: 2048
  max_label_names_per_series: 30

  max_local_series_per_tenant: 1000000
  max_global_series_per_tenant: 1000000
